adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Application-2.jpg
adx_parentpageid: d7cf5ad7-f47d-f011-b4cc-7c1e52476cc1
adx_partialurl: Application-2.jpg
adx_publishingstateid: 241260d1-f47d-f011-b4cc-7c1e52476cc1
adx_summary: ''
adx_title: ''
adx_webfileid: 3f8d200f-aede-46e9-8335-6cf13db336a4
annotationid: 2e9c089e-f87d-f011-b4cc-7c1e52476cc1
filename: Application-2.jpg
isdocument: true
mimetype: image/jpeg
objectid: 3f8d200f-aede-46e9-8335-6cf13db336a4
objecttypecode: adx_webfile
